SCREEN_WIDTH = 3840
SCREEN_HEIGHT = 2160

ASTEROID_MIN_RADIUS = 200
ASTEROID_KINDS = 3
ASTEROID_SPAWN_RATE = 0.8  # seconds
ASTEROID_MAX_RADIUS = ASTEROID_MIN_RADIUS * ASTEROID_KINDS

PLAYER_RADIUS = 100
PLAYER_TURN_SPEED = 300
PLAYER_SPEED = 2000
PLAYER_SHOOT_COOLDOWN = 0.3

SHOT_RADIUS = 30
PLAYER_SHOOT_SPEED = 1000
